/* Interface text (buttons, headings, form labels) in English and Arabic. */
export const STRINGS = {
  en: {
    nav: { about: 'About', cuisines: 'Cuisines', services: 'Services', events: 'Events', ramadan: 'Ramadan', locations: 'Our brands', book: 'Book your event', menu: 'Menu', close: 'Close' },
    lang: 'العربية',
    langLabel: 'Switch to Arabic',
    hero: {
      eyebrow: 'Catering · Kuwait',
      title1: 'Five kitchens.',
      title2: 'One table.',
      lead: 'Arabic, Lebanese, Chinese, Japanese and Mediterranean catering for weddings, banks, hotels, chalets and every gathering in between.',
      cta: 'Book your event',
      cta2: 'See the menus',
      scroll: 'Scroll',
    },
    marquee: ['Weddings', 'Banking', 'Hotels', 'Chalets', 'Iftar', 'Suhoor', 'Gatherings', 'Conferences', 'Private parties'],
    about: {
      eyebrow: 'Who we are',
      title: 'A Kuwaiti catering house with *a world on the menu.*',
      p1: 'Green Hills started with one idea: a host should not have to choose between the food their family grew up with and the food their guests travel for. So we built one team that cooks five cuisines properly, each with its own chefs, its own spices and its own fire.',
      p2: 'We plan the menu with you, cook it fresh in our central kitchen, bring the stations, the staff and the tableware, and leave the venue the way we found it.',
      pillars: [
        { t: 'Cooked fresh, on the day', d: 'Nothing is reheated from the day before.' },
        { t: 'One team, start to finish', d: 'The person who plans your menu is there on the night.' },
        { t: 'Any size', d: 'A diwaniya of twenty or a hall of a thousand.' },
      ],
    },
    cuisines: {
      eyebrow: 'What we cook',
      title: 'Choose a kitchen, *or mix all five.*',
      sample: 'Sample menu',
      note: 'Every menu is tailored to your event. These are a few favourites.',
      ask: 'Ask for this menu',
    },
    services: {
      eyebrow: 'What we do',
      title: 'How we *serve it*',
    },
    events: {
      eyebrow: 'Every occasion',
      title: 'Whatever the occasion, *we know the drill.*',
      cta: 'Book this',
    },
    ramadan: {
      eyebrow: 'Ramadan with Green Hills',
      title: 'Iftar, ghabga and suhoor, *delivered and served.*',
      lead: 'Daily iftar for offices and families, ghabga nights for teams and majlis, and suhoor spreads that last until dawn. Book early: Ramadan dates fill first.',
      cta: 'Plan a Ramadan event',
    },
    reels: {
      eyebrow: 'From our kitchen',
      title: 'Watch it *happen*',
      play: 'Play video with sound',
      closeVideo: 'Close video',
    },
    process: {
      eyebrow: 'How booking works',
      title: 'Three steps to *a full table*',
      steps: [
        { t: 'Tell us about the event', d: 'Date, guests, venue and the kind of food you have in mind.' },
        { t: 'We shape the menu', d: 'Our events team calls you with a menu and a quote that fit.' },
        { t: 'We cook, serve and clear', d: 'Our team arrives early, serves through the night and leaves the venue clean.' },
      ],
    },
    locations: {
      eyebrow: 'Visit our brands',
      title: 'Taste our food any day *at our restaurants.*',
      directions: 'Directions',
      call: 'Call',
      hotline: 'Hotline',
      follow: 'Follow on Instagram',
      branches: (n) => (n === 1 ? '1 branch' : `${n} branches`),
      coverage: 'Catering delivered and served across all six governorates',
    },
    book: {
      eyebrow: 'Book your event',
      title: 'Tell us about *your event.*',
      lead: 'It takes about two minutes. Our events team gets back to you to shape the menu and confirm the details.',
      steps: ['Event', 'Venue', 'Your details', 'Review'],
      stepOf: (a, b) => `Step ${a} of ${b}`,
      next: 'Continue',
      back: 'Back',
      submit: 'Send booking request',
      sending: 'Sending…',
      edit: 'Edit',
      f: {
        eventType: 'Type of event',
        date: 'Event date',
        time: 'Start time',
        guests: 'Number of guests',
        service: 'Service style',
        cuisines: 'Cuisines',
        cuisinesHint: 'Choose one or more.',
        budget: 'Budget per guest',
        venueType: 'Venue',
        governorate: 'Governorate',
        area: 'Area',
        areaPh: 'e.g. Salmiya',
        address: 'Venue name or address',
        addressPh: 'Hall, hotel, block, street, house',
        extras: 'Also needed',
        name: 'Full name',
        phone: 'Mobile number',
        phonePh: '5XXX XXXX',
        email: 'Email',
        emailPh: 'name@example.com',
        company: 'Company or bank',
        companyHint: 'Optional',
        contactMethod: 'Best way to reach you',
        notes: 'Anything else we should know?',
        notesPh: 'Allergies, theme, VIP guests, timings…',
        consent: 'I agree that Green Hills may contact me about this booking.',
        optional: 'Optional',
      },
      err: {
        required: 'This field is required.',
        pick: 'Choose an option.',
        pickOne: 'Choose at least one.',
        date: 'Choose a date from tomorrow onwards.',
        guests: 'Enter between 10 and 5,000 guests.',
        phone: 'Enter an 8-digit Kuwaiti number.',
        email: 'Enter a valid email address.',
        consent: 'Please tick this box so we can contact you.',
        server: 'We couldn’t send your request. Check your connection and try again.',
        fix: 'Please fix the highlighted fields.',
      },
      done: {
        title: 'Request received',
        ref: 'Your reference',
        text: 'Thank you. Our events team will contact you shortly to shape your menu and confirm the details.',
        again: 'Book another event',
      },
      reviewTitle: 'Check your details',
      guestsUnit: 'guests',
    },
    footer: {
      tag: 'Catering for every occasion in Kuwait.',
      rights: 'All rights reserved.',
      top: 'Back to top',
    },
    skip: 'Skip to content',
  },

  ar: {
    nav: { about: 'من نحن', cuisines: 'المطابخ', services: 'خدماتنا', events: 'المناسبات', ramadan: 'رمضان', locations: 'مطاعمنا', book: 'احجز مناسبتك', menu: 'القائمة', close: 'إغلاق' },
    lang: 'English',
    langLabel: 'التبديل إلى الإنجليزية',
    hero: {
      eyebrow: 'تموين وضيافة · الكويت',
      title1: 'خمسة مطابخ.',
      title2: 'مائدة واحدة.',
      lead: 'تموين عربي، لبناني، صيني، ياباني ومتوسطي للأعراس والبنوك والفنادق والشاليهات، ولكل مناسبة بينها.',
      cta: 'احجز مناسبتك',
      cta2: 'تصفّح القوائم',
      scroll: 'مرّر',
    },
    marquee: ['أعراس', 'بنوك', 'فنادق', 'شاليهات', 'فطور رمضان', 'سحور', 'تجمعات', 'مؤتمرات', 'حفلات خاصة'],
    about: {
      eyebrow: 'من نحن',
      title: 'بيت ضيافة كويتي، *وقائمته من كل العالم.*',
      p1: 'بدأت جرين هيلز بفكرة واحدة: المضيف لا يجب أن يختار بين الأكل الذي تربّى عليه وبين الأكل الذي يسافر ضيوفه من أجله. لذلك بنينا فريقًا واحدًا يطبخ خمسة مطابخ كما يجب، لكل مطبخ طهاته وبهاراته وناره.',
      p2: 'نخطط القائمة معك، ونطهوها طازجة في مطبخنا المركزي، ونحضر المحطات وطاقم الضيافة والأواني، ونترك المكان كما وجدناه.',
      pillars: [
        { t: 'طازج في يوم المناسبة', d: 'لا شيء يُعاد تسخينه من اليوم السابق.' },
        { t: 'فريق واحد من البداية للنهاية', d: 'من يخطط قائمتك يكون حاضرًا ليلة المناسبة.' },
        { t: 'أي حجم', d: 'ديوانية لعشرين شخصًا أو قاعة لألف.' },
      ],
    },
    cuisines: {
      eyebrow: 'ماذا نطبخ',
      title: 'اختر مطبخًا، *أو امزج الخمسة.*',
      sample: 'قائمة مقترحة',
      note: 'كل قائمة تُصمم حسب مناسبتك. هذه بعض الأطباق المفضلة.',
      ask: 'اطلب هذه القائمة',
    },
    services: {
      eyebrow: 'ماذا نقدّم',
      title: 'أساليب *التقديم*',
    },
    events: {
      eyebrow: 'لكل مناسبة',
      title: 'مهما كانت المناسبة، *نعرف كيف نديرها.*',
      cta: 'احجز',
    },
    ramadan: {
      eyebrow: 'رمضان مع جرين هيلز',
      title: 'فطور وغبقة وسحور، *نوصلها ونقدّمها.*',
      lead: 'فطور يومي للمكاتب والعائلات، وليالي غبقة للفرق والمجالس، وموائد سحور حتى الفجر. احجز مبكرًا، فمواعيد رمضان تمتلئ أولًا.',
      cta: 'خطط لمناسبة رمضانية',
    },
    reels: {
      eyebrow: 'من مطبخنا',
      title: 'شاهد كيف *نطبخ*',
      play: 'شغّل الفيديو مع الصوت',
      closeVideo: 'إغلاق الفيديو',
    },
    process: {
      eyebrow: 'كيف يتم الحجز',
      title: 'ثلاث خطوات *لمائدة عامرة*',
      steps: [
        { t: 'أخبرنا عن مناسبتك', d: 'التاريخ، عدد الضيوف، المكان ونوع الأكل الذي تفكر فيه.' },
        { t: 'نصمم القائمة', d: 'يتصل بك فريق المناسبات بقائمة وعرض سعر يناسبانك.' },
        { t: 'نطبخ ونقدّم ونرتّب', d: 'يصل فريقنا مبكرًا، ويقدّم طوال المناسبة، ويترك المكان نظيفًا.' },
      ],
    },
    locations: {
      eyebrow: 'زوروا مطاعمنا',
      title: 'تذوّقوا أكلنا كل يوم *في مطاعمنا.*',
      directions: 'الاتجاهات',
      call: 'اتصل',
      hotline: 'الخط الساخن',
      follow: 'تابعنا على إنستغرام',
      branches: (n) => (n === 1 ? 'فرع واحد' : n === 2 ? 'فرعان' : `${['٠','١','٢','٣','٤','٥','٦','٧','٨','٩'][n] || n} فروع`),
      coverage: 'نقدّم خدمات التموين والضيافة في جميع المحافظات الست',
    },
    book: {
      eyebrow: 'احجز مناسبتك',
      title: 'أخبرنا عن *مناسبتك.*',
      lead: 'يستغرق الأمر دقيقتين تقريبًا. يتواصل معك فريق المناسبات لتصميم القائمة وتأكيد التفاصيل.',
      steps: ['المناسبة', 'المكان', 'بياناتك', 'المراجعة'],
      stepOf: (a, b) => `الخطوة ${a} من ${b}`,
      next: 'متابعة',
      back: 'رجوع',
      submit: 'أرسل طلب الحجز',
      sending: 'جارٍ الإرسال…',
      edit: 'تعديل',
      f: {
        eventType: 'نوع المناسبة',
        date: 'تاريخ المناسبة',
        time: 'وقت البدء',
        guests: 'عدد الضيوف',
        service: 'أسلوب التقديم',
        cuisines: 'المطابخ',
        cuisinesHint: 'اختر واحدًا أو أكثر.',
        budget: 'الميزانية للضيف',
        venueType: 'المكان',
        governorate: 'المحافظة',
        area: 'المنطقة',
        areaPh: 'مثال: السالمية',
        address: 'اسم المكان أو العنوان',
        addressPh: 'القاعة، الفندق، القطعة، الشارع، المنزل',
        extras: 'نحتاج أيضًا',
        name: 'الاسم الكامل',
        phone: 'رقم الهاتف',
        phonePh: '5XXX XXXX',
        email: 'البريد الإلكتروني',
        emailPh: 'name@example.com',
        company: 'الشركة أو البنك',
        companyHint: 'اختياري',
        contactMethod: 'أفضل طريقة للتواصل',
        notes: 'هل هناك شيء آخر يجب أن نعرفه؟',
        notesPh: 'حساسية طعام، طابع المناسبة، ضيوف كبار، التوقيت…',
        consent: 'أوافق على أن تتواصل معي جرين هيلز بخصوص هذا الحجز.',
        optional: 'اختياري',
      },
      err: {
        required: 'هذا الحقل مطلوب.',
        pick: 'اختر خيارًا.',
        pickOne: 'اختر خيارًا واحدًا على الأقل.',
        date: 'اختر تاريخًا من الغد فصاعدًا.',
        guests: 'أدخل عددًا بين ١٠ و٥٠٠٠ ضيف.',
        phone: 'أدخل رقمًا كويتيًا من ٨ أرقام.',
        email: 'أدخل بريدًا إلكترونيًا صحيحًا.',
        consent: 'يرجى التأشير هنا لنتمكن من التواصل معك.',
        server: 'تعذّر إرسال طلبك. تحقق من الاتصال وحاول مرة أخرى.',
        fix: 'يرجى تصحيح الحقول المحددة.',
      },
      done: {
        title: 'وصلنا طلبك',
        ref: 'رقم الطلب',
        text: 'شكرًا لك. سيتواصل معك فريق المناسبات قريبًا لتصميم قائمتك وتأكيد التفاصيل.',
        again: 'احجز مناسبة أخرى',
      },
      reviewTitle: 'راجع بياناتك',
      guestsUnit: 'ضيف',
    },
    footer: {
      tag: 'تموين وضيافة لكل مناسبة في الكويت.',
      rights: 'جميع الحقوق محفوظة.',
      top: 'العودة للأعلى',
    },
    skip: 'تخطَّ إلى المحتوى',
  },
}
