# Generated by Django 5.1.4 on 2026-10-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("quoted", "Quote sent"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("wedding", "Weddings & engagements"),
                            ("corporate", "Corporate & banking"),
                            ("gathering", "Family gatherings"),
                            ("hotel", "Hotels & venues"),
                            ("chalet", "Chalets & outdoor"),
                            ("ramadan", "Ramadan"),
                            ("party", "Private parties"),
                            ("conference", "Conferences & exhibitions"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_date", models.DateField(db_index=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("guests", models.PositiveIntegerField()),
                (
                    "service_style",
                    models.CharField(
                        choices=[
                            ("buffet", "Open buffet"),
                            ("plated", "Plated service"),
                            ("live", "Live stations"),
                            ("lifestyle", "Lifestyle & boxes"),
                            ("unsure", "Help me choose"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cuisines", models.JSONField(default=list)),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("lt10", "Under 10 KWD / guest"),
                            ("10-20", "10 – 20 KWD / guest"),
                            ("20-35", "20 – 35 KWD / guest"),
                            ("gt35", "35 KWD + / guest"),
                            ("unsure", "Not sure yet"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("chalet", "Chalet / camp"),
                            ("hotel", "Hotel"),
                            ("hall", "Wedding hall"),
                            ("office", "Office / bank"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "governorate",
                    models.CharField(
                        choices=[
                            ("capital", "Capital"),
                            ("hawalli", "Hawalli"),
                            ("farwaniya", "Farwaniya"),
                            ("mubarak", "Mubarak Al-Kabeer"),
                            ("ahmadi", "Ahmadi"),
                            ("jahra", "Jahra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("area", models.CharField(max_length=80)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("extras", models.JSONField(blank=True, default=list)),
                ("full_name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=160)),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="company / bank"
                    ),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[
                            ("call", "Phone call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        default="whatsapp",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=1500)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Only visible to staff.",
                        verbose_name="team notes",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "booking request",
                "verbose_name_plural": "booking requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
